library(dplyr)
library(utils)
subjetTest  <- read.table("subject_test.txt",  header = F, col.names = "subjet")
subjetTrain <- read.table("subject_train.txt", header = F, col.names = "subjet")
dataTest  <- read.table("X_test.txt",  header = F)
dataTrain <- read.table("X_train.txt", header = F)
activyTest  <- read.table("y_test.txt",  header = F, col.names = "activity")
activyTrain <- read.table("y_train.txt", header = F, col.names = "activity")
activity <- rbind(activyTest, activyTrain)
data     <- rbind(dataTest, dataTrain)
tidyData   <- rbind(subjetTest, subjetTrain)
rm("subjetTest","subjetTrain","dataTest","dataTrain","activyTest","activyTrain")
tidyData$mean <- apply(data, 1, mean)
tidyData$sd   <- apply(data, 1, sd)
activities <- c("WALKING","WALKING UPSTAIRS","WALKING DOWNSTAIRS","SITTING",
            "STANDING", "LAYING")
tidyData$activity <- factor(activity$activity,labels = activities)
by_activity_subject <- group_by(tidyData, activity, subjet)
tidyData2 <- summarise(by_activity_subject, mean=mean(mean))
write.table(tidyData2, "result.txt",row.names = FALSE)
